# Notebook #2: Descriptive Statistics & Initial EDA

In this notebook, we perform some basic exploratory data analysis in the cleaned dataset to understand size, composition, and relationships relevant to our research questions (i.e., demographics, student status, funding).

## 1.0. Import Libraries

In [1]:
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go
import plotly.io as pio

<hr>

## 2.0. Import the Cleaned 'district_and_expenses' CSV Data

In [2]:
# Import and store the cleaned DataFrame from the 'district_and_expenses.csv' file
district_and_expenses = pd.read_csv('district_and_expenses.csv')

# Display the imported 'district_and_expenses' DataFrame
display(district_and_expenses)

Fed ID  District Code      CDS Code County Name District Type  \
0    601770.0          61119  1.611190e+12     Alameda       Unified   
1    601860.0          61127  1.611270e+12     Alameda       Unified   
2    604740.0          61143  1.611430e+12     Alameda       Unified   
3    607800.0          61150  1.611500e+12     Alameda       Unified   
4    612630.0          61168  1.611680e+12     Alameda       Unified   
..        ...            ...           ...         ...           ...   
927       NaN          76349           NaN   Mendocino    Elementary   
928       NaN          40261           NaN  Santa Cruz    Elementary   
929       NaN          40246           NaN      Sonoma    Elementary   
930       NaN          40253           NaN      Sonoma    Elementary   
931       NaN          40717           NaN  Stanislaus    Elementary   

    Grade Low  Grade High Grade Low Census  Grade High Census  \
0          KG          12               KG                 12   
1          KG          12               KG                 12   
2          KG          12               KG                 12   
3          KG          12               KG                 12   
4          KG          12               KG                 12   
..        ...         ...              ...                ...   
927        KG          12               KG                  8   
928        KG           5               KG                  5   
929        KG          12               KG                  6   
930        KG           8               KG                  6   
931        KG          12               KG                  8   

             Assistance Status  ... Students with Disabilities (%)  \
0           General Assistance  ...                      12.200000   
1           General Assistance  ...                       9.000000   
2           General Assistance  ...                      12.000000   
3           General Assistance  ...                      11.000000   
4           General Assistance  ...                      12.500000   
..                         ...  ...                            ...   
927         General Assistance  ...                      14.883721   
928         General Assistance  ...                      14.636480   
929                        NaN  ...                      17.717921   
930                        NaN  ...                      17.340181   
931  Differentiated Assistance  ...                      12.710381   

     Socioeconomically Disadvantaged  Socioeconomically Disadvantaged (%)  \
0                             4035.0                            38.200000   
1                             1122.0                            31.400000   
2                             2508.0                            27.600000   
3                             3686.0                            38.800000   
4                              327.0                            54.500000   
..                               ...                                  ...   
927                            243.0                            56.511628   
928                           2304.0                            36.734694   
929                           3326.0                            45.018950   
930                           7541.0                            50.959589   
931                          24229.0                            77.086316   

                                        District Label  \
0                            Alameda Unified (Alameda)   
1                        Albany City Unified (Alameda)   
2                           Berkeley Unified (Alameda)   
3                      Castro Valley Unified (Alameda)   
4                              Emery Unified (Alameda)   
..                                                 ...   
927  Arena Union Elementary/Point Arena Joint Union...   
928       Santa Cruz City Elementary/High (Santa Cruz)   
929  Petaluma City Elementary/Joint Union High (Son...   
930            

<hr>

## 3.0. Descriptive Statistics

### 3.1. Distribution of Demographic Percentages

We looked into the distribution of student demographic percentages across California school districts. To understand the diversity and equity across California school districts, we examine the distributions of key student demographic percentages, which include: racial/ethnic groups, English learners, and student status populations (i.e., foster, socioeconomically disadvantaged (SED), migrant, homeless).

In [3]:
# Keep a list of the student demographic column names
DEMOGRAPHICS = ['African American (%)', 'American Indian (%)', 'Asian (%)','Filipino (%)',
                'Hispanic (%)', 'Pacific Islander (%)', 'White (%)', 'Two or More Races (%)',
                'English Learner (%)', 'Foster (%)', 'Homeless (%)', 'Migrant (%)', 
                'Students with Disabilities (%)', 'Socioeconomically Disadvantaged (%)']

# Display the descriptive statistics for the student demographic columns using 'demographic' values
district_and_expenses[DEMOGRAPHICS].describe()

African American (%)  American Indian (%)   Asian (%)  Filipino (%)  \
count            932.000000           932.000000  932.000000    932.000000   
mean               2.333693             1.766325    5.868692      1.270682   
std                4.047831             6.849491   10.816395      2.362522   
min                0.000000             0.000000    0.000000      0.000000   
25%                0.300000             0.100000    0.500000      0.000000   
50%                0.900000             0.300000    1.500000      0.500000   
75%                2.400000             0.800000    5.700000      1.400000   
max               44.200000           100.000000   69.400000     25.800000   

       Hispanic (%)  Pacific Islander (%)   White (%)  Two or More Races (%)  \
count    932.000000            932.000000  932.000000             932.000000   
mean      47.828038              0.282077   34.178112               5.135629   
std       28.105139              0.507898   24.890993               4.336854   
min        0.000000              0.000000    0.000000               0.000000   
25%       21.900000              0.000000   10.975000               1.600000   
50%       45.850000              0.100000   31.780233               4.500000   
75%       70.825000              0.300000   55.325000               7.500000   
max      100.000000              6.500000  100.000000              25.000000   

       English Learner (%)  Foster (%)  Homeless (%)  Migrant (%)  \
count           932.000000  932.000000    932.000000   932.000000   
mean             16.667545    0.536182      3.679393     1.454324   
std              14.767007    1.279515      5.112967     3.779724   
min               0.000000    0.000000      0.000000     0.000000   
25%               5.200000    0.100000      0.500000     0.000000   
50%              13.100000    0.300000      1.956210     0.000000   
75%              23.925000    0.600000      4.700000     0.900000   
max              75.000000   30.000000     40.800000    49.400000   

       Students with Disabilities (%)  Socioeconomically Disadvantaged (%)  
count                      932.000000                           932.000000  
mean                        12.928851                            58.668789  
std                          4.479624                            24.187314  
min                          0.000000                             0.800000  
25%                         10.400000                            41.075000  
50%                         13.000000                            61.150000  
75%                         15.000000                            78.925000  
max                         66.700000                           100.000000

The summary statistics above provide a quick overview of the distributions of student demographic percentages across California school districts. This information can be used to identify the range of values, central tendencies, and spread of each demographic group.

Some insights:
- High variability in Hispanic (%) (std ~28%) suggests concentrated or sparse populations in certain areas
- High mean in Socioeconomically Disadvantaged (~58.7%) indicates a significant number of SED students across districts.
- Moderately high mean in English Learners (mean ~16.7%) indicates a significant number of English learners across CA districts.
- Low means for Foster (~0.53%) & Migrant (~1.4%) indicate these are niche demographic challenges


### 3.2. Distribution of the 'Expense per ADA' Column

We wanted to understand the spread of per-student spending, the crux of our research questions. 

In [4]:
district_and_expenses['Expense per ADA'].describe()

count       932.000000
mean      22181.055837
std       11107.346413
min        9951.740000
25%       17181.642500
50%       19742.790000
75%       22965.720000
max      139026.730000
Name: Expense per ADA, dtype: float64

The overall distribution of `'Expense per ADA'` shows n = 932 districts with:
- Mean ~$22,181
- Median ~$19,743
- Standard Deviation ~$11,107

When taking into account the mininum (9,952) and maximum (139,027), the mean & median indicate a **right-skewed distribution**. This means that most of the data is "lumped" on the lower end of the scale, with the mean higher than the median due to a small number of very high-spending outliers.

The interquartile range (IQR = Q3 (22,966) - Q1 (17,182) = $5,784) captures the range of the middle 50% of the data.

### 3.3. Breakdown of 'Expense  per ADA' by 'District Type' Columns

We considered how `'District Type'` (i.e., `'Elementary'`, `'High'`, `'Unified'`) may influence per-pupil spending due to differing curricula, facilities, or student needs.

In [5]:
district_and_expenses.groupby('District Type')['Expense per ADA'].mean()

District Type
Elementary    22642.697093
High          20855.198451
Unified       21763.458696
Name: Expense per ADA, dtype: float64

`'Elementary'` districts spend the most per ADA on average, while `'High'` school districts spend the least, with Unified in between.

These differences are not huge, but are noticeable and may be statistically significant. We will consider this in our regression analysis to determine if `'District Type'` is a significant predictor of `'Expense per ADA'`.

### 3.4. Breakdown of 'Expense per ADA' by 'Locale' Columns

District `'Locale'` (i.e., `'City'`, `'Town'`, `'Rural'`, `'Suburban'`) often correlates with economic factors that may affect district budgets.

We considered grouping by `'Locale'` to understand if there are significant differences in per-pupil spending across location types, which may be due to housing costs, transportation, or staffing challenges in sparser or more remote areas.

In [6]:
district_and_expenses.groupby('Locale')['Expense per ADA'].mean()

Locale
City            20187.757820
Not Reported    22276.770000
Rural           25534.498475
Suburban        20471.701115
Town            19805.738153
Name: Expense per ADA, dtype: float64

`'Rural'` locales (25,534) showed the highest average `'Expense per ADA'`. This may be because rural districts may face structural cost factors (e.g., transportation, staffing, housing) that increase per-pupil spending.

### 3.5. Correlations between 'Expense per ADA' and Demographic Percentage Columns

We wanted to explore potential relationships between spending and student demographics. To do this, we computed the Pearson correlations between `'Expense per ADA'` values and demographic percentages.

With the `pandas.corr()` method, the default correlation is the Pearson method, which measures the linear relationship between two variables.

In [7]:
district_and_expenses[['Expense per ADA'] + DEMOGRAPHICS].corr()

Expense per ADA  African American (%)  \
Expense per ADA                             1.000000             -0.015822   
African American (%)                       -0.015822              1.000000   
American Indian (%)                         0.223872             -0.083401   
Asian (%)                                  -0.119730              0.047436   
Filipino (%)                               -0.108340              0.204436   
Hispanic (%)                               -0.054040              0.069447   
Pacific Islander (%)                       -0.053364              0.292803   
White (%)                                   0.056764             -0.266314   
Two or More Races (%)                       0.029782              0.042404   
English Learner (%)                         0.035026             -0.015922   
Foster (%)                                  0.163290              0.089812   
Homeless (%)                                0.106771             -0.019211   
Migrant (%)                                 0.039248             -0.138319   
Students with Disabilities (%)              0.188632              0.109889   
Socioeconomically Disadvantaged (%)         0.143856              0.145167   

                                     American Indian (%)  Asian (%)  \
Expense per ADA                                 0.223872  -0.119730   
African American (%)                           -0.083401   0.047436   
American Indian (%)                             1.000000  -0.100695   
Asian (%)                                      -0.100695   1.000000   
Filipino (%)                                   -0.075441   0.397292   
Hispanic (%)                                   -0.218426  -0.256856   
Pacific Islander (%)                           -0.065433   0.176154   
White (%)                                       0.021522  -0.202308   
Two or More Races (%)                           0.105848   0.193719   
English Learner (%)                            -0.170176  -0.033464   
Foster (%)                                      0.159801  -0.103466   
Homeless (%)                                    0.041118  -0.139262   
Migrant (%)                                    -0.060554  -0.158101   
Students with Disabilities (%)                  0.190101  -0.153105   
Socioeconomically Disadvantaged (%)             0.075872  -0.360027   

                                     Filipino (%)  Hispanic (%)  \
Expense per ADA                         -0.108340     -0.054040   
African American (%)                     0.204436      0.069447   
American Indian (%)                     -0.075441     -0.218426   
Asian (%)                                0.397292     -0.256856   
Filipino (%)                             1.000000     -0.040743   
Hispanic (%)                            -0.040743      1.000000   
Pacific Islander (%)                     0.361735     -0.045171   
White (%)                               -0.259234     -0.824279   
Two or More Races (%)                    0.114708     -0.679685   
English Learner (%)                      0.033892      0.786666   
Foster (%)                              -0.083292     -0.033007   
Homeless (%)                            -0.067410      0.189019   
Migrant (%)                             -0.116461      0.449230   
Students with Disabilities (%)          -0.023331     -0.071258   
Socioeconomically Disadvantaged (%)     -0.153410      0.670924   

                                     Pacific Islander (%)  White (%)  \
Expense per ADA                                 -0.053364   0.056764   
African American (%)                             0.292803  -0.266314   
American Indian (%)                             -0.065433   0.021522   
Asian (%)                                        0.176154  -0.202308   
Filipino (%)                                     0.361735  -0.259234   
Hispanic (%)                                    -0.045171  -0.824279   
Pacific Islander (%)                             1.000000  -0.129050   
Wh

The Pearson correlation matrix between Expense per ADA & demographics showed generally weak linear associations. More analysis is needed to understand if these relationships are statistically significant (see notebook 5). 

<hr>

## 4.0. Initial EDA

### 4.1. Box Plot - Distribution of Total Enrollment

A box plot will help us visualize enrollment distributions, spread, and outliers.

In [8]:
fig_enroll_box = px.box(
    district_and_expenses, 
    x='Enroll Total', 
    title='Box Plot of Total Enrollment')
    
fig_enroll_box.show()

This box plot confirms our earlier observation that the distribution of **total enrollment is right-skewed**, with a few districts having much higher enrollments than the rest.

### 4.2. Box Plot - Distribution of the 'Expense per ADA' Column

A box plot for `'Expense per ADA'` will help us visualize the distribution and spread of per-pupil spending.

In [9]:
fig_exp_box = px.box(
    district_and_expenses, 
    x='Expense per ADA', 
    title='Box Plot of Expense per ADA')

fig_exp_box.show()

Similar to our analysis in Section 3.2, this box plot confirms that the distribution of `'Expense per ADA'` values is **right-skewed**. There are a few high-spending outliers.

### 4.3. Scatter Plot - 'Expense per ADA'  vs. Total Enrollment (Without Los Angeles Unified)

By removing Los Angeles Unified, we can better visualize the patterns among other districts.

In [10]:
scatter_drop_LA = district_and_expenses[district_and_expenses['District Name'] != 'Los Angeles Unified']

fig_scatter = px.scatter(
    scatter_drop_LA, 
    x='Enroll Total', 
    y='Expense per ADA',
    color='District Type',
    opacity=0.5,
    trendline='ols',
    hover_name='District Name',
    title='Expense per ADA vs. Total Enrollment',
    subtitle='Without LA Unified')

fig_scatter.show()

The relationship between size and spending appears weak to moderately negative or flat, suggesting that larger districts may spend less per student than smaller districts do.

### 4.4. Scatter Plot - 'Expense per ADA' vs. Percentage of Socioeconomically Disadvantaged Pupils

We wanted to know whether school districts with more socioeconomically disadvantaged students spend more per ADA.

In [11]:
fig_econ_dis = px.scatter(
    district_and_expenses,
    x='Socioeconomically Disadvantaged (%)',
    y='Expense per ADA',
    hover_data=['District Name', 'County Name'],
    title='Expense per ADA vs. Socioeconomically Disadvantaged (%)',
    subtitle='Weak Positive Correlation',
    labels={'Socioeconomically Disadvantaged (%)': 'Socioeconomically Disadvantaged (%)', 'Expense per ADA': 'Expense per ADA ($)'},
    trendline='ols',
    trendline_color_override='red'
)
fig_econ_dis.show()

The OLS trendline suggests that the relationship appears weakly positive.

In other words, districts with higher proportions of socioeconomically disadvantaged students tend to have slightly higher per-ADA spending on average.

This may hint at the possibility that districts with more socioeconomically disadvantaged students may be provided with additional resources and support by the state, which could explain the higher per-ADA spending. This may also be an effect of the LCFF.

### 4.5. Scatter Plot - 'Expense per ADA' vs. Percentage of Migrant Pupils

We wondered whether migrant students may impact per-pupil spending due to their unique needs and the resources required to support them.

In [12]:
fig_migrant = px.scatter(
    district_and_expenses,
    x='Migrant (%)',
    y='Expense per ADA',
    hover_data=['District Name', 'County Name'],
    title='Expense per ADA vs. Migrant (%)',
    labels={'Migrant (%)': 'Migrant (%)', 'Expense per ADA': 'Expense per ADA ($)'},
    trendline='ols',
    trendline_color_override='red'
)
fig_migrant.show()

The R-squared value is extremely low (0.0015), suggesting that there may be no linear relationship between the percentage of migrant students and per-pupil spending. However, we will do further regression analysis to determine if this relationship is statistically significant.

### 4.6. Scatter Plot - 'Expense per ADA' vs. Percentage of English Learner Pupils

We wanted to know whether English Learners (in a similar manner as Migrant demographics) may impact per-pupil spending due to their unique needs and the resources required to support them.

In [13]:
fig_homeless = px.scatter(
    district_and_expenses,
    x='English Learner (%)',
    y='Expense per ADA',
    hover_data=['District Name', 'County Name'],
    title='Expense per ADA vs. English Learner (%)',
    labels={'English Learner (%)': 'English Learner (%)', 'Expense per ADA': 'Expense per ADA ($)'},
    trendline='ols',
    trendline_color_override='red'
)
fig_homeless.show()

The R_squared value (0.0012) is extremely low, suggesting that there may be little or no linear relationship between the percentage of English Learners and per-pupil spending. However, we will do further regression analysis to determine if this relationship is statistically significant.

<a style='text-decoration:none;line-height:16px;display:flex;color:#5B5B62;padding:10px;justify-content:end;' href='https://deepnote.com?utm_source=created-in-deepnote-cell&projectId=246b06f0-3e45-45e3-acef-efea2bae7701' target="_blank">
 </img>
Created in <span style='font-weight:600;margin-left:4px;'>Deepnote</span></a>